# Generated by Django 5.2.16 on 2026-07-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
