# Generated by Django 5.2.12 on 2026-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('kind', models.CharField(choices=[('past', 'Past'), ('present', 'Present'), ('future', 'Future'), ('milestone', 'Milestone')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
