# Generated by Django 5.2.16 on 2026-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourmap', '0003_relationship_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappin',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mappin',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='mappin',
            name='lng',
        ),
        migrations.AlterField(
            model_name='mappin',
            name='unlock_at',
            field=models.DateTimeField(blank=True, help_text='Určuje pořadí bodu na cestě a datum, které se u něj zobrazí. Celá cesta je vždy viditelná.', null=True, verbose_name='Datum na cestě'),
        ),
    ]
