# Generated by Django 5.2.12 on 2026-07-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('album', models.CharField(blank=True, max_length=100)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_by_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='jar.unlockcode')),
            ],
            options={
                'ordering': ['album', 'taken_on'],
            },
        ),
    ]
