# Generated by Django 5.2.12 on 2026-07-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('available_at', models.DateTimeField()),
                ('is_big', models.BooleanField(default=False)),
                ('has_code', models.BooleanField(default=False)),
                ('unlock_code', models.CharField(blank=True, max_length=100)),
                ('web_content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='UnlockCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('target_type', models.CharField(choices=[('time_capsule', 'Time Capsule'), ('map_pin', 'Map Pin'), ('gallery_album', 'Gallery Album'), ('chapter', 'Chapter'), ('love_wall_theme', 'Love Wall Theme')], max_length=20)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LetterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='jar.letter')),
            ],
        ),
    ]
