# Generated by Django 5.2.16 on 2026-07-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='challenge_content',
            field=models.TextField(blank=True, help_text='Online výzva/vzkaz, který se odemkne až po zadání správného kódu z dopisu.'),
        ),
        migrations.AddField(
            model_name='letterstate',
            name='code_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='letterstate',
            name='code_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='unlock_code',
            field=models.CharField(blank=True, help_text='Kód napsaný uvnitř fyzického dopisu. Zadá ho online, až dopis otevře.', max_length=100),
        ),
    ]
