# Generated by Django 5.2.12 on 2026-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('teaser', models.CharField(max_length=300)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('is_locked_default', models.BooleanField(default=True)),
                ('body', models.TextField(blank=True)),
                ('manually_unlocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
